version: "3.9"
services:
  web:
    image: nginx
    build: ./public/
    volumes: 
      - ./public:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/:/etc/nginx/certs/
    ports:
      - "443:443"
      - "80:80"