version: "3.9"
services:
  web:
    image: nginx
    build: ./public/
    volumes: 
      - ./public:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/:/etc/nginx/certs/
    ports:
      - "443:443"
      - "80:80"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./config:/mosquitto/data
      - ./config:/mosquitto/log
    ports:
      - "1884:1884"
      - "1883:1883"